<?php
$listarray = array ( array ( 'label' => 'Bezeichnung',
                             'name' => 'bez',
                             'width' => 50, 
                             'type' => 'text',
                             'dbfield' => 'fldname' ),                     
                     array ( 'label' => 'Adresse',
                             'name' => 'adresse',
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldaddress' ),
                     array ( 'label' => 'Latitude',
                             'name' => 'lat',
                             'width' => 10, 
                             'type' => 'int',
                             'dbfield' => 'fldlat' ),
                     array ( 'label' => 'Longitude',
                             'name' => 'lon',
                             'width' => 10, 
                             'type' => 'int',
                             'dbfield' => 'fldlng' ),
                     array ( 'label' => 'Type',
                             'name' => 'type',
                             'fieldhide' => 'true', 
                             'width' => 20, 
                             'type' => 'text',
                             'dbfield' => 'fldtype' ));

$pararray = array ( 'headline' => 'Spielpl&aumltze',
                    'dbtable' => 'tblmarkers',
                    'orderby' => '',
                    'strwhere' => '',
                    'fldindex' => 'fldindex');
?>